### ISSUE TITLE
BinaryBroadcastMessage aren't correctly decoded

### ISSUE THREAD

**Issue by pyrog** [tbsalling/aismessages#14]
`!AIVDM,1,1,,B,84QjLb1Kf9pf<SwKAO4t2km7Hk:d=m2hq;rPtVJosMCFfTkrNkcf,0*39`

http://www.maritec.co.za/tools/aisvdmvdodecoding/ decode:

Field | Value
-- | --
DAC | 366
FI | 56

http://www.aggsoft.com/ais-decoder.htm decode:

Field | Value
-- | --
Application ID | 23480

Wich is 0x5BB8
```
0x5BB8 >> 0x08 = 0x16E = 366 (DAC)
0x5BB8 && 0x3F = 0x038 =  56 (FI)
```

http://ais.tbsalling.dk decode:

Field | Value
-- | --
DAC | 1467
FI | 8

… which is different from previous results.

DAC 1467 is not documented on the web.
DAC 366 FI 56 are referenced in this talk: https://en.wikipedia.org/wiki/Talk:Automatic_identification_system#Military_vessels
> For the US "blue force" transmissions, they are done with type 8 messages, DAC 366, and FIDs 56 (256 bytes) and 57 (512 bytes). These are sent not only by military vessels, but also Homeland Security (USCG) and law enforcement vessels.

Also, `getBinaryData()` return only the first 4 bits of the data.

**Comment by tbsalling** [comment]
Brilliant work. Thank you.
