### ISSUE TITLE
Call to AISMessage#dataFields is slow

### ISSUE THREAD

**Issue by hbs** [tbsalling/aismessages#16]
The reason is that dataFields uses introspection to determine the various fields and in the process calls the method isComplex which calls Class.getPackage which is slowing the overall execution.

Calls to getPackage should be replaced by something less resource hungry.

**Comment by tbsalling** [comment]
Could you contribute a pull request solving this - preferably just inside this method and without changing or removing unit tests (additions welcome :-))?
