### ISSUE TITLE
JDK 9 compatibility is making the library unusable on projects which need to stick to JDK8

### ISSUE THREAD

**Issue by hbs** [tbsalling/aismessages#30]
The recent release of 3.0.2 on maven repositories has rendered the library unusable for all applications which must still use JDK8 due to incompatibilities in their dependencies.

**Comment by tbsalling** [comment]
Yes - I am aware of this problem.

As soon as I get time (or someone contributes) - the current version will be extended to support a [multi-version JAR file](https://www.javaworld.com/article/3184029/java-language/java-9s-other-new-enhancements-part-4-multi-release-jar-files.html) with support for Java 8 and 9. 

Until then your options are a) to stick with version 2.x binaries and/or b) to use the source code tagged ["last-java8-commit"](https://github.com/tbsalling/aismessages/tree/last-java8-commit). If backports to version 2.x.x (Java 8) are required at some time I will branch from this point.

**Comment by tbsalling** [comment]
Sorry - but due to lack of available work effort, I have decided to only support the latest JDK LTS version, which currently is Java 11. 

Users who - for different reasons - are stuck with older Java version will have to use AISmessages 2.x.x.
