### ISSUE TITLE
AIS ChannelManagement Message (Type 22): southWestLongitude is missing 1 bit

### ISSUE THREAD

**Issue by M0r13n** [tbsalling/aismessages#31]
I believe that the SouthWestLongitude field should be 17 bits wide, but it's only 16 (138-122). 
In this [line](https://github.com/tbsalling/aismessages/blob/8e8420e1ecd5e3d02336f0e255bd15e90b958549/src/main/java/dk/tbsalling/aismessages/ais/messages/ChannelManagement.java#L99) 138 should be replaced with 139.

**Comment by tbsalling** [comment]
Hi @M0r13n,

Thanks for your input. I think you are right. Your observation is compliant with table 55, p. 134, of "Recommendation ITU-R M.1371-5" this field is stated to 17 bits.

I would like to invite you to become a contributor by submitting a pull request which fixes this and also includes a unit test to make sure that we interprete this type of messsage correctly.

Thanks,
/Thomas.

**Comment by tbsalling** [comment]
This fixed has been included in AISmessages 3.0.4 which is now available on Maven Central - https://mvnrepository.com/artifact/dk.tbsalling/aismessages/3.0.4
