### ISSUE TITLE
Incorrect SpeedOverGround?

### ISSUE THREAD

**Issue by chelliwell** [tbsalling/aismessages#33]
Hi,
I've been using your online decoder today, and have just had an unexpected result:
!AIVDM,1,1,,B,C69DqeP0Ar8;JH3R6<4O7wWPl@:62L>jcaQgh0000000?104222P,0*32
is reporting Speed as 3.5, but I think (based on trying a couple of other decoders) that it should be 7.1?
I've already been through several Type 1/2/3 messages without a problem - this was the first Type 19 I've tried so far.

**Comment by tbsalling** [comment]
Hi @chelliwell - thanks for reporting this.

The NMEA string you reported can be expanded into this bit-string: 

`010011000110001001010100111001101101100000000000010001111010001000001011011010011000000011100010000110001100000100011111000111111111100111100000110100010000001010000110000010011100001110110010101011101001100001101111110000000000000000000000000000000000000000000000001111000001000000000100000010000010000010100000`

According to [ITU 1371.5](https://www.itu.int/dms_pubrec/itu-r/rec/m/R-REC-M.1371-5-201402-I!!PDF-E.pdf), sect. 3.17,  the speed is represented by bits 46-55 (both inclusive), i.e. `0001000111`. This is equivalent to decimal value 71.

The SOG field is defined as "Speed over ground in 1/10 knot steps (0-102.2 knots)
1 023 = not available, 1 022 = 102.2 knots or higher" - so a decimal value of 71 is equivalent to 7.1 knots.

So your assessment is correct. I'll provide a bug fix shortly. 

Thanks again,
/Thomas.

**Comment by tbsalling** [comment]
Fixed by commit 20080d4e615f8d6f945f160b9d220917e575c08f

**Comment by tbsalling** [comment]
So - this is now fixed in AISmessages; it will still take a while before it's available in the online decoder.
