### ISSUE TITLE
MMSI, IMO should be a String

### ISSUE THREAD

**Issue by panoet** [tbsalling/aismessages#45]
If we look how AIS data will be used, I don't think it is good idea to declare MMSI and IMO as an Integer. Will be better if it declared as String.

Often, AIS data has been compromised and there is possibility to have MMSI and IMO that not fulfill the standard. 

It is highly possible we catch an AIS data starting with 0, but it is not a coastal station nor group of a ships, e.g 012345678.
I just worried if it declared as Integer, it will be shrunk to "12345678" because of leading zero in Integer is meaningless. And we will get wrong MID is we use that shrunk MMSI.

**Comment by tbsalling** [comment]
Hi @panoet 

Thank you for your feedback! 

AISmessages has been running in production for 10+ years and probably decoded millions of AIS messages. The format of the MMSI field has never caused any problems.

I have debugged and seen many strange, and non-conformant AIS messages over the years - and I agree with you that one can see strange things and that the decoder must be robust to this. However the MMSI field can logically only consist of digits (be a number). The protocol simply does not allow for anything else. Therefore I believe that the correct interpretation of the MMSI field can safely always be an int.

If your concern is to be able to read the leading 3 digits (even for numbers shorter than 9 digits - for instance a group of ships starting with a leading 0, or a shore station starting with 00), you can easily format the MMSI number as a 9-digit String and then extract the first three:

```
        MMSI mmsi = MMSI.valueOf(12345678);
        String mmsiAsString = String.format("%09d", mmsi.getMMSI());
        String mid = mmsiAsString.substring(0, 3);
        System.out.println(mid);
```

which prints `012`.

I can add a new method to the MMSI class with these lines.

**Comment by tbsalling** [comment]
I have added MMSI#as9DigitString() - https://github.com/tbsalling/aismessages/commit/b454b1a510ea7fd9336f30da92db731fca418972.

I have built a release and published it as dk.tbsalling:aismessages:3.2.5 on Maven Central. Usually it takes 24-48 hours before the published artifacts are available there.

**Comment by panoet** [comment]
Your approach work in "normal" condition, but potentially make data interpretation incorrect.
I just captured my AIS Satellite Data and catch a null execption when decoding MID, wiith these MMSI: 098529401 (this mmsi is already processed using String.format as you suggest). I guess the real data is 98529401 and String format added leading zero in it.

The problem is, I checked the data on my Marine Traffic account (I have premium satellite subscription), and found an AIS record for 98529401). Of course I know, it is invalid MMSI. 

But, in my experience, it is better if we take the data "as is". Adding or removing the leading zero in MMSI field is not good decision I believe. Therefore, it will better to treat mmsi, imo as categorical data instead of numerical data.

**Comment by panoet** [comment]
Some MMSI you can check on marinetraffic.com:
9129846, 98529401, 3224442, 98346571, 9118928.

We can't just add leading zero to them. If we did it, data can't be trusted anymore. Better to let the data as is, so our data will be identical with another data sources.

Just FYI, maybe you've forgot. Taking the MID from the mmsi field does not always from index 0 to 3. It can be from index 0, 1, 2, or 3 depends on the mmsi field itself. This rule make adding leading zero will be make another data bias.

**Comment by tbsalling** [comment]
No, I have not forgotten. And I do not agree that these fields should be strings. But if that suits you application better you can always fork the project and change whatever you want.

The purpose of AISmessages is to be a protocol-level decoder with no knowledge of the application that uses it. At the protocol layer MMSI numbers are 9 digit. By definition (M.585-9 Annex 1, ITU 1371-5 sect. 3.3.7.2.1). So AIS messages conformant to the spec have MMSI numbers 30 bits long - 2^30= 1.073.741.824 - enough to hold 9 digits. If there is a 10th it is ignored. So MMSI by definition cannot be 7 digits. But they can have leading 0s.

However marinetraffic ends up showing 7 I do not know - that is an application level issue. The immediate assumption would be that the leading digits are 0.
