### ISSUE TITLE
Receiving invalid AIS Message while it can be decoded using another decoder.

### ISSUE THREAD

**Issue by panoet** [tbsalling/aismessages#47]
Actually I am trying to migrate from AisDecoder (ArunDale) to your library. I never got and error using AisDecoder, it can decode all the Satellite AIS stream I have with 0 rejected / error from millions data received.

Using your library, I always got these kind of error:
```
Oct 10, 2022 2:50:10 PM dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader run
WARNING: Received invalid AIS message: "\s:rORBCOMM999,c:1665388207*26\!AIVDM,1,1,,,H8Ih`40l58hTr0AD622222222200,2*4E"
Oct 10, 2022 2:50:13 PM dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader run
WARNING: Received invalid AIS message: "\g:2-2-1089*5D\!AIVDM,2,2,7,,mWVP0@@;ONOeD,0*08"
Oct 10, 2022 2:50:16 PM dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader run
WARNING: Received invalid AIS message: "\s:rORBCOMM999,c:1665388213*23\!AIVDM,1,1,,,H7tD750e=210U<<E>22222222200,2*6F"
Oct 10, 2022 2:50:16 PM dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader run
WARNING: Received invalid AIS message: "\g:2-2-1142*5B\!AIVDM,2,2,0,,689P000<<@OeD,0*2E"
Oct 10, 2022 2:50:18 PM dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader run
WARNING: Received invalid AIS message: "\s:rORBCOMM999,c:1665388218*28\!AIVDM,1,1,,,H7tKep@H>0u8<PTB222222222200,2*01"
Oct 10, 2022 2:50:18 PM dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader run
WARNING: Received invalid AIS message: "\s:rORBCOMM999,c:1665388216*26\!AIVDM,1,1,,,H7tKep@H>0u8<PTB222222222200,2*01"
Oct 10, 2022 2:50:20 PM dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader run
WARNING: Received invalid AIS message: "\s:rORBCOMM999,c:1665388217*27\!AIVDM,1,1,,,H8HugK0QB08D59=>222222222200,2*64"
```

And often after some errors, no data will be processed anymore. Is there any way to analyze those error? Because it is almost impossible to look for causes using only those WARNING.

I tried to decode it using another tools i.e. [maritec](https://www.maritec.co.za/aisvdmvdodecoding) and [aggsoft](https://www.aggsoft.com/ais-decoder.htm#)

**Comment by tbsalling** [comment]
`!AIVDM,1,1,,,H7tKep@H>0u8<PTB222222222200,2*01` is a good example of a non-compliant message from the wild. It is a type 24 - ClassBCSStaticDataReport. To the best of my knowledge these should be exactly 158, 160 or 168 bits long; not 166 like this one.

If you can find an official reference on how to safely decode a message of type 24 with length 166 bits I shall be happy to add it to the library.

**Comment by tbsalling** [comment]
A good way to analyze these is to clone AISmessage and add a unit test to e.g. in AISMessageTest.java:

```
 @Test
    public void canHandleObservedNMEAMessage() {
        assertThrows(InvalidMessage.class, () -> AISMessage.create(NMEAMessage.fromString("!AIVDM,1,1,,,H7tKep@H>0u8<PTB222222222200,2*01")));
    }
```

**Comment by panoet** [comment]
I just

```
public class AisMessageTest {
    @Test
    public void canHandleObservedNMEAMessage() {
        assertThrows(InvalidMessage.class, () -> AISMessage.create(NMEAMessage.fromString("\\s:rORBCOMM999,c:1665388213*23\\!AIVDM,1,1,,,H7tD750e=210U<<E>22222222200,2*6F")));
    }
}
```

And it passed the test...

**Comment by panoet** [comment]
> `!AIVDM,1,1,,,H7tKep@H>0u8<PTB222222222200,2*01` is a good example of a non-compliant message from the wild. It is a type 24 - ClassBCSStaticDataReport. To the best of my knowledge these should be exactly 158, 160 or 168 bits long; not 166 like this one.
> 
> If you can find an official reference on how to safely decode a message of type 24 with length 166 bits I shall be happy to add it to the library.

Where do you get those number (158, 160, and 168)? According to [ITU-R M.1371-5](https://www.itu.int/rec/R-REC-M.1371-5-201402-I/en), there is 2 possible of Message 24
1. Message 24A : 160 bits data, you can check Table 78
2. Message 24B : 168 bits data, you can check Table 79.

There, in Table 79 mentioned that 2 last bits of Message 24B as **spare**. If we "ignore" those bits, we will get 166 bits in total.
And I think it is safe to decode 166 bits of Message 24B, consider the last 2 bits are spare.

**Comment by tbsalling** [comment]
Ok, so I have added a leaner parsing of your message. You can pull the latest or wait ~36h for AISMessages v3.2.6 to be available in [Maven Central](https://mvnrepository.com/artifact/dk.tbsalling/aismessages).
